version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - IDENTITY=${IDENTITY}
      - SECRET_KEY=${SECRET_KEY}
      - GAME_SECRET=${GAME_SECRET}
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/budokan
    # depends_on:
    #   - db
    volumes:
      - .:/app
      - /app/node_modules

  # db:
  #   image: postgres:15-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=budokan
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: